### PR TITLE
Add ISP GCC support

### PR DESCRIPTION
**Pull request by danchouzhou**
1. Modify __align(4) into __attribute __((aligned(4))), #pragma data_alignment=4 for __ICCARM __
2. Modify unsigned int into uint32_t in fmc_user prevent from warning.
3. Remove unuse interrupt vector in the startup file if necessary.

All of the code doesn't tested, need to be confirm through the target board. 
May add NuEclipse project metadata will be ideal.

### CODE REVIEW

**Comment by yachen** [comment]
Hi, What's the image size you got building these samples with GCC? I tested ISP_UART and got a 7kB image, which is larger than 4kB LDROM size.

**Comment by ZaleYu** [comment]
Hi YA sir:
According to his post, the size would be 3868 bytes by using gcc-arm-none-eabi-10.3-2021.07.
https://github.com/OpenNuvoton/M480BSP/issues/6#issuecomment-903696605

Sincerely, 
Zale Yu

**Comment by danchouzhou** [comment]
Hello Yi-An Chen: 

For ISP_UART, I got 2464 bytes with gcc-arm-none-eabi-10.3-2021.07 compiler.

Cheers, 
Danny

**Comment by danchouzhou** [comment]
Hello Yi-An Chen:

Are you using the NuEclipse to build the project? If you got 7KB code size, it may link some unused stuff (ex. sys.c, clk.c, uart.c, retarget.c) into it. Please check the Makefile in my branch. 

Cheers, 
Danny

**Comment by ZaleYu** [comment]
Hi Danny:
Did you compile your project directly by the toolchain without NuEclipse?

Sincerely,
Zale Yu

**Comment by danchouzhou** [comment]
Hello Zale Yu, 

Yes I do.

Cheers, 
Danny

**Comment by yachen** [comment]
retarget.c turns out to be the culprit. Linker is unable to remove the unused I/O functions once retarget.c is include in the project.

**Comment by ZaleYu** [comment]
Hi YA sir:
Could you remove retarget.c from the project of NuEclipse?

Sincerely,
Zale Yu

**Pull request closed without merging**
